//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class tbl_admin
{
    public int admin_id { get; set; }
    public string admin_adi { get; set; }
    public string sifre { get; set; }
}

public partial class tbl_hayvan
{
    public int id { get; set; }
    public Nullable<int> il_id { get; set; }
    public Nullable<int> kucukbas { get; set; }
    public Nullable<int> buyukbas { get; set; }
    public string hayvan_tarih { get; set; }

    public virtual tbl_iller tbl_iller { get; set; }
}

public partial class tbl_iletisim
{
    public int iletisim_id { get; set; }
    public string yorumcu_adi { get; set; }
    public string yorumcu_soyadi { get; set; }
    public string gorus_ve_oneriler { get; set; }
    public string tc_kimlik_no { get; set; }
    public string dogum_yili { get; set; }
}

public partial class tbl_iller
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_iller()
    {
        this.tbl_hayvan = new HashSet<tbl_hayvan>();
        this.tbl_meyve = new HashSet<tbl_meyve>();
        this.tbl_sebze = new HashSet<tbl_sebze>();
        this.tbl_tarim_urunleri = new HashSet<tbl_tarim_urunleri>();
        this.tbl_tarim_alani_ve_yuz_olcumu = new HashSet<tbl_tarim_alani_ve_yuz_olcumu>();
    }

    public int il_id { get; set; }
    public string il_adi { get; set; }
    public Nullable<int> yuzolcumu { get; set; }
    public Nullable<int> nufus { get; set; }
    public Nullable<int> tarim_alani { get; set; }
    public string il_tarih { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_hayvan> tbl_hayvan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_meyve> tbl_meyve { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_sebze> tbl_sebze { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_tarim_urunleri> tbl_tarim_urunleri { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_tarim_alani_ve_yuz_olcumu> tbl_tarim_alani_ve_yuz_olcumu { get; set; }
}

public partial class tbl_meyve
{
    public int id { get; set; }
    public Nullable<int> il_id { get; set; }
    public Nullable<int> elma { get; set; }
    public Nullable<int> armut { get; set; }
    public Nullable<int> erik { get; set; }
    public Nullable<int> kayısı { get; set; }
    public Nullable<int> kiraz { get; set; }
    public string meyve_tarih { get; set; }

    public virtual tbl_iller tbl_iller { get; set; }
}

public partial class tbl_sebze
{
    public int id { get; set; }
    public Nullable<int> il_id { get; set; }
    public Nullable<int> lahana { get; set; }
    public Nullable<int> domates { get; set; }
    public Nullable<int> fasulye { get; set; }
    public Nullable<int> salatalik { get; set; }
    public Nullable<int> yesil_biber { get; set; }
    public string sebze_tarih { get; set; }

    public virtual tbl_iller tbl_iller { get; set; }
}

public partial class tbl_tarim_alani_ve_yuz_olcumu
{
    public int tarim_alani_ve_yuz_olcumu_id { get; set; }
    public Nullable<int> il_id { get; set; }
    public Nullable<int> nufus_bilgisi { get; set; }
    public Nullable<int> yuz_olcumu { get; set; }
    public Nullable<int> tarim_alani { get; set; }
    public string tarim_alani_ve_yuz_olcumu_tarih { get; set; }

    public virtual tbl_iller tbl_iller { get; set; }
}

public partial class tbl_tarim_urunleri
{
    public int id { get; set; }
    public Nullable<int> il_id { get; set; }
    public Nullable<int> yesil_ot { get; set; }
    public Nullable<int> mısır { get; set; }
    public Nullable<int> bugday { get; set; }
    public Nullable<int> patates { get; set; }
    public Nullable<int> arpa { get; set; }
    public string tarim_urunleri_tarih { get; set; }

    public virtual tbl_iller tbl_iller { get; set; }
}
