//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DbWebEntities : DbContext
{
    public DbWebEntities()
        : base("name=DbWebEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<tbl_admin> tbl_admin { get; set; }
    public virtual DbSet<tbl_hayvan> tbl_hayvan { get; set; }
    public virtual DbSet<tbl_iller> tbl_iller { get; set; }
    public virtual DbSet<tbl_meyve> tbl_meyve { get; set; }
    public virtual DbSet<tbl_sebze> tbl_sebze { get; set; }
    public virtual DbSet<tbl_tarim_urunleri> tbl_tarim_urunleri { get; set; }
    public virtual DbSet<tbl_tarim_alani_ve_yuz_olcumu> tbl_tarim_alani_ve_yuz_olcumu { get; set; }
    public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
}
